service: aws-serverless-ts-template

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev # Default stage to be used. Default is "dev"
  region: us-east-1 # Default region to be used. Default is "us-east-1"
  memorySize: 256
  timeout: 10

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  
custom:
  prune:
    automatic: true
    number: 1
  webpack:
    includeModules: true

package:
  excludeDevDependencies: false
  individually: true
  patterns: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  hellolambda:
    handler: src/lambda.handler
    events:
      - httpApi:
          method: GET
          path: /hello

